bind-address = "127.0.0.1:8088"

[meta]
dir = "/tmp/meta"
logging-enabled = false

[data]
dir = "/tmp/data"
wal-dir = "/tmp/wal"

[[graphite]]
enabled = true
database = "graphite"
bind-address = ":2003"
tags = [ "region=us-east", "zone=1c" ]
templates = [ "*.app env.service.resource.measurement", "server.*" ]

